services:
  angular-tutorial:
    container_name: angular-web
    build:
      context: ./docker-angular
      dockerfile: Dockerfile
    #command: 'sh /sh/start.sh'
    ports:
      - 4200:4200
    volumes:
      - ./docker-angular/project:/usr/local/project
    tty: true

volumes:
  angular_node_modules:
